from .active_region import ActiveRegion, active_region_from_slices, pack_active_fields, unpack_active_fields
from .elliptic import FourierHelmholtzOperator, build_fourier_helmholtz_operator, solve_fourier_helmholtz
from .implicit import (
    ImplicitStepInfo,
    SparseDifferenceQuotientGroup,
    SparseDifferenceQuotientPlan,
    backward_euler_residual,
    bdf2_residual,
    build_locality_sparsity,
    build_modulo_color_groups,
    build_sparse_difference_quotient_jacobian,
    difference_quotient_step_size,
    prepare_sparse_difference_quotient_plan,
    solve_jax_linearized_newton_system,
    solve_matrix_free_newton_system,
    solve_sparse_newton_system,
)

__all__ = [
    "ActiveRegion",
    "FourierHelmholtzOperator",
    "ImplicitStepInfo",
    "SparseDifferenceQuotientGroup",
    "SparseDifferenceQuotientPlan",
    "active_region_from_slices",
    "backward_euler_residual",
    "bdf2_residual",
    "build_fourier_helmholtz_operator",
    "build_locality_sparsity",
    "build_modulo_color_groups",
    "build_sparse_difference_quotient_jacobian",
    "difference_quotient_step_size",
    "pack_active_fields",
    "prepare_sparse_difference_quotient_plan",
    "solve_fourier_helmholtz",
    "solve_jax_linearized_newton_system",
    "solve_matrix_free_newton_system",
    "solve_sparse_newton_system",
    "unpack_active_fields",
]
