"""Regenerate README movie assets into `examples/assets/readme/`.

The repository keeps long-form documentation assets under `docs/assets/images/`.
However, the README is intended to be self-contained and to point to assets that are
generated by scripts in `examples/`. This script:

1) runs the relevant example movie scripts (HW2D, DRB2D, DRB2D hot-ion, FCI/DRB3D 3D torus)
2) copies + optionally optimizes the resulting GIFs into `examples/assets/readme/`

The goal is: small, stable, reproducible, and visually informative movies that show
linear growth and nonlinear saturation on laptop hardware.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


def _maybe_optimize_gif_with_ffmpeg(path: Path) -> None:
    ffmpeg = shutil.which("ffmpeg")
    if ffmpeg is None:
        print("[make_readme_movie_assets] ffmpeg not found; skipping GIF optimization")
        return

    with tempfile.TemporaryDirectory() as td:
        td_path = Path(td)
        palette = td_path / "palette.png"
        optimized = td_path / "optimized.gif"

        vf = "fps=12,scale=420:-1:flags=lanczos"
        subprocess.run(
            [
                ffmpeg,
                "-y",
                "-i",
                str(path),
                "-vf",
                f"{vf},palettegen=max_colors=96:stats_mode=diff",
                str(palette),
            ],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        subprocess.run(
            [
                ffmpeg,
                "-y",
                "-i",
                str(path),
                "-i",
                str(palette),
                "-lavfi",
                f"{vf}[x];[x][1:v]paletteuse=dither=bayer:bayer_scale=4",
                str(optimized),
            ],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )

        old_size = path.stat().st_size
        new_size = optimized.stat().st_size
        if new_size < old_size:
            shutil.copy2(optimized, path)
            print(
                f"[make_readme_movie_assets] optimized GIF: {old_size / 1e6:.2f} MB -> {new_size / 1e6:.2f} MB"
            )
        else:
            print("[make_readme_movie_assets] optimization not smaller; keeping original GIF")


def _run(cmd: list[str], *, cwd: Path, env: dict[str, str]) -> None:
    print("[make_readme_movie_assets] running:", " ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=cwd, check=True, env=env)


def main() -> None:
    repo_root = Path(__file__).resolve().parents[3]
    out_dir = repo_root / "_out_make_readme_movies"
    out_dir.mkdir(parents=True, exist_ok=True)

    env = dict(**os.environ)
    env["PYTHONPATH"] = str(repo_root / "src") + (
        (":" + env["PYTHONPATH"]) if "PYTHONPATH" in env else ""
    )

    dst_dir = repo_root / "examples/assets/readme"
    dst_dir.mkdir(parents=True, exist_ok=True)

    # 0) Geometry overview schematic (static PNG for the top of the README).
    _run(
        [
            sys.executable,
            str(repo_root / "examples/assets/scripts/make_readme_geometry_overview.py"),
        ],
        cwd=repo_root,
        env=env,
    )

    # 1) HW2D
    hw_out = out_dir / "hw2d"
    _run(
        [
            sys.executable,
            str(repo_root / "examples/08_nonlinear_hw2d/hw2d_movie.py"),
            "--out",
            str(hw_out),
            "--nx",
            "48",
            "--ny",
            "48",
            "--dt",
            "0.01",
            "--tmax",
            "80.0",
            "--save-stride",
            "100",
            "--seed",
            "0",
        ],
        cwd=repo_root,
        env=env,
    )
    shutil.copy2(hw_out / "movie.gif", dst_dir / "hw2d_turbulence.gif")
    _maybe_optimize_gif_with_ffmpeg(dst_dir / "hw2d_turbulence.gif")

    # 2) DRB2D Kelvin–Helmholtz (README)
    kh_out = out_dir / "drb2d_kh"
    _run(
        [
            sys.executable,
            str(repo_root / "examples/08_nonlinear_drb2d/drb2d_kelvin_helmholtz.py"),
            "--out",
            str(kh_out),
            "--gif",
            "--no-analysis",
            "--tmax",
            "30.0",
            "--save-stride",
            "12",
        ],
        cwd=repo_root,
        env=env,
    )
    shutil.copy2(kh_out / "kh_vorticity.gif", dst_dir / "drb2d_kh.gif")
    _maybe_optimize_gif_with_ffmpeg(dst_dir / "drb2d_kh.gif")

    # 3) DRB2D Hermes-2 blob2d proxy
    hermes_out = out_dir / "drb2d_hermes2_blob"
    _run(
        [
            sys.executable,
            str(repo_root / "examples/08_nonlinear_drb2d/drb2d_hermes2_blob2d.py"),
            "--out",
            str(hermes_out),
            "--gif",
            "--no-analysis",
            "--tmax",
            "10.0",
            "--save-stride",
            "16",
            "--forcing-amp",
            "3e-3",
            "--mu-lin-omega",
            "0.005",
            "--Dn",
            "5e-4",
            "--DOmega",
            "8e-4",
            "--DTe",
            "5e-4",
            "--curvature",
            "-1.0",
        ],
        cwd=repo_root,
        env=env,
    )
    shutil.copy2(hermes_out / "hermes2_blob2d.gif", dst_dir / "drb2d_hermes2_blob.gif")
    _maybe_optimize_gif_with_ffmpeg(dst_dir / "drb2d_hermes2_blob.gif")

    # 4) DRB2D hot-ion
    hot_out = out_dir / "drb2d_hot_ion"
    _run(
        [
            sys.executable,
            str(repo_root / "examples/08_nonlinear_drb2d/drb2d_hot_ion_movie.py"),
            "--out",
            str(hot_out),
            "--nx",
            "64",
            "--ny",
            "64",
            "--dt",
            "0.015",
            "--tmax",
            "22.0",
            "--save-stride",
            "16",
            "--solver",
            "dopri5",
            "--fixed-step",
            "--seed",
            "0",
        ],
        cwd=repo_root,
        env=env,
    )
    shutil.copy2(hot_out / "movie.gif", dst_dir / "drb2d_hot_ion_turbulence.gif")
    _maybe_optimize_gif_with_ffmpeg(dst_dir / "drb2d_hot_ion_turbulence.gif")

    # 5) FCI/DRB3D (true 3D toroidal geometry): periodic + open-field-line variants.
    #
    # These are minimal (n, Omega) runs intended to demonstrate the toroidal-plane mapping
    # and 3D rendering in a short, robust example. For the full multiphysics DRB3D branch
    # diagnostics, see `examples/09_fci/`.
    fci3d_periodic = out_dir / "fci_drb3d_toroidal_periodic"
    _run(
        [
            sys.executable,
            str(repo_root / "examples/10_3d/toroidal_fci_drb3d_min_movie.py"),
            "--out",
            str(fci3d_periodic),
            "--no-open-field-line",
            "--nphi",
            "10",
            "--nR",
            "12",
            "--nZ",
            "12",
            "--dt",
            "0.01",
            "--nsteps",
            "600",
            "--save-every",
            "20",
            "--seed",
            "0",
        ],
        cwd=repo_root,
        env=env,
    )
    shutil.copy2(fci3d_periodic / "movie.gif", dst_dir / "fci_drb3d_periodic_turbulence.gif")
    _maybe_optimize_gif_with_ffmpeg(dst_dir / "fci_drb3d_periodic_turbulence.gif")

    fci3d_sheath = out_dir / "fci_drb3d_toroidal_sheath"
    _run(
        [
            sys.executable,
            str(repo_root / "examples/10_3d/toroidal_fci_drb3d_min_movie.py"),
            "--out",
            str(fci3d_sheath),
            "--open-field-line",
            "--nphi",
            "10",
            "--nR",
            "12",
            "--nZ",
            "12",
            "--dt",
            "0.01",
            "--nsteps",
            "600",
            "--save-every",
            "20",
            "--seed",
            "0",
        ],
        cwd=repo_root,
        env=env,
    )
    shutil.copy2(fci3d_sheath / "movie.gif", dst_dir / "fci_drb3d_sheath_turbulence.gif")
    _maybe_optimize_gif_with_ffmpeg(dst_dir / "fci_drb3d_sheath_turbulence.gif")

    print(f"[make_readme_movie_assets] wrote assets to {dst_dir}")


if __name__ == "__main__":
    main()
