"""Independent manufactured-source utilities for the real-HSX MMS lane.

This module contains no FCI map construction.  The production harness supplies
the maps generated by the HSX geometry builder.  The continuum reference below
uses the same smooth ``MetricEvaluator`` and MAKEGRID field, but evaluates
``L_parallel`` independently of the owner graph.
"""
from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
from typing import Any, Callable

import numpy as np

SOURCE_REFERENCE_SCHEMA = "drbx.real_hsx_mms_source_reference"
SOURCE_REFERENCE_VERSION = 2
FIELD_RADIAL_ETA = "radial_eta"
FIELD_ANGULAR_X = "angular_x"
FIELD_MIXED_Y_ETA = "mixed_y_eta"
FIELD_CONSTANT = "constant"
FIELD_KIND_CHOICES = (FIELD_RADIAL_ETA, FIELD_ANGULAR_X, FIELD_MIXED_Y_ETA, FIELD_CONSTANT)
RADIAL_PROFILE_WALL = "wall"
RADIAL_PROFILE_SMOOTH_AXIS = "smooth_axis"
RADIAL_PROFILE_CHOICES = (RADIAL_PROFILE_WALL, RADIAL_PROFILE_SMOOTH_AXIS)
_RADIAL_PROFILE_ALIASES = {
    "wall": RADIAL_PROFILE_WALL,
    "wall_compatible": RADIAL_PROFILE_WALL,
    "u2_one_minus_u_to_4": RADIAL_PROFILE_WALL,
    "u2(1-u)^4": RADIAL_PROFILE_WALL,
    "smooth_axis": RADIAL_PROFILE_SMOOTH_AXIS,
    "smooth-axis": RADIAL_PROFILE_SMOOTH_AXIS,
    "u2_one_minus_u2_to_4": RADIAL_PROFILE_SMOOTH_AXIS,
    "u2(1-u^2)^4": RADIAL_PROFILE_SMOOTH_AXIS,
}


@dataclass(frozen=True)
class ManufacturedField:
    """Axis- and wall-compatible parallel manufactured field.

    ``wall`` preserves the original ``u^2 (1-u)^4`` profile.  The companion
    ``smooth_axis`` profile is ``u^2 (1-u^2)^4``; its radial derivatives are
    analytic so the continuum source and exact time evolution remain tied to
    the selected profile.
    """

    m: int = 1
    amplitude: float = 0.2
    lam: float = 0.3
    chi: float = 0.1
    eta_period: float = 2.0 * np.pi
    radial_profile: str = RADIAL_PROFILE_WALL
    field_kind: str = FIELD_RADIAL_ETA

    def __post_init__(self) -> None:
        object.__setattr__(self, "radial_profile", self.normalize_radial_profile(self.radial_profile))
        kind = str(self.field_kind).strip().lower().replace("-", "_")
        if kind not in FIELD_KIND_CHOICES:
            raise ValueError(f"unknown manufactured field {self.field_kind!r}; choose one of {', '.join(FIELD_KIND_CHOICES)}")
        object.__setattr__(self, "field_kind", kind)

    @staticmethod
    def normalize_radial_profile(profile: str) -> str:
        key = str(profile).strip().lower()
        try:
            return _RADIAL_PROFILE_ALIASES[key]
        except KeyError as exc:
            choices = ", ".join(RADIAL_PROFILE_CHOICES)
            raise ValueError(f"unknown radial profile {profile!r}; choose one of {choices}") from exc

    @property
    def radial_formula(self) -> str:
        if self.field_kind in (FIELD_ANGULAR_X, FIELD_MIXED_Y_ETA):
            return "u(1-u^2)^4"
        if self.field_kind == FIELD_CONSTANT:
            return "1"
        if self.radial_profile == RADIAL_PROFILE_SMOOTH_AXIS:
            return "u^2(1-u^2)^4"
        return "u^2(1-u)^4"

    def _radial(self, u: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        if self.field_kind in (FIELD_ANGULAR_X, FIELD_MIXED_Y_ETA):
            one = 1.0 - u * u
            value = u * one**4
            first = one**3 * (1.0 - 9.0 * u * u)
            second = 24.0 * u * one**2 * (3.0 * u * u - 1.0)
            return value, first, second
        if self.field_kind == FIELD_CONSTANT:
            return np.ones_like(u), np.zeros_like(u), np.zeros_like(u)
        if self.radial_profile == RADIAL_PROFILE_SMOOTH_AXIS:
            one = 1.0 - u * u
            value = u * u * one**4
            first = 2.0 * u * one**3 * (1.0 - 5.0 * u * u)
            second = 2.0 * one**2 * (1.0 - 22.0 * u * u + 45.0 * u**4)
            return value, first, second
        one = 1.0 - u
        value = u * u * one**4
        first = 2.0 * u * one**4 - 4.0 * u * u * one**3
        second = 2.0 * one**4 - 16.0 * u * one**3 + 12.0 * u * u * one**2
        return value, first, second

    def value_gradient_hessian(self, points: Any) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        q = np.asarray(points, dtype=np.float64).reshape((-1, 3))
        u, theta, eta = q.T
        radial, radial_u, radial_uu = self._radial(u)
        wave = 2.0 * np.pi * float(self.m) / float(self.eta_period)
        angle = wave * eta
        if self.field_kind == FIELD_ANGULAR_X:
            angular = np.cos(theta); angular_1 = -np.sin(theta); angular_2 = -angular
            toroidal = np.ones_like(eta); toroidal_1 = np.zeros_like(eta); toroidal_2 = np.zeros_like(eta)
        elif self.field_kind == FIELD_MIXED_Y_ETA:
            angular = np.sin(theta); angular_1 = np.cos(theta); angular_2 = -angular
            toroidal = np.sin(angle); toroidal_1 = wave * np.cos(angle); toroidal_2 = -wave * wave * toroidal
        elif self.field_kind == FIELD_CONSTANT:
            angular = np.ones_like(theta); angular_1 = np.zeros_like(theta); angular_2 = np.zeros_like(theta)
            toroidal = np.ones_like(eta); toroidal_1 = np.zeros_like(eta); toroidal_2 = np.zeros_like(eta)
        else:
            angular = np.ones_like(theta); angular_1 = np.zeros_like(theta); angular_2 = np.zeros_like(theta)
            toroidal = np.sin(angle); toroidal_1 = wave * np.cos(angle); toroidal_2 = -wave * wave * toroidal
        value = radial * angular * toroidal
        gradient = np.stack((radial_u * angular * toroidal, radial * angular_1 * toroidal, radial * angular * toroidal_1), axis=-1)
        hessian = np.zeros((q.shape[0], 3, 3), dtype=np.float64)
        hessian[:, 0, 0] = radial_uu * angular * toroidal
        hessian[:, 1, 1] = radial * angular_2 * toroidal
        hessian[:, 2, 2] = radial * angular * toroidal_2
        hessian[:, 0, 1] = hessian[:, 1, 0] = radial_u * angular_1 * toroidal
        hessian[:, 0, 2] = hessian[:, 2, 0] = radial_u * angular * toroidal_1
        hessian[:, 1, 2] = hessian[:, 2, 1] = radial * angular_1 * toroidal_1
        return value, gradient, hessian

    @property
    def formula(self) -> str:
        return {
            FIELD_RADIAL_ETA: f"{self.radial_formula} sin(m eta)",
            FIELD_ANGULAR_X: "x(1-u^2)^4",
            FIELD_MIXED_Y_ETA: "y(1-u^2)^4 sin(m eta)",
            FIELD_CONSTANT: "1",
        }[self.field_kind]

    def time_factor(self, time: float) -> float:
        return float(np.exp(-float(self.lam) * float(time)))
