from ..runtime import configure_jax_runtime

configure_jax_runtime()

from .runner import NativeRunResult, run_config_case, run_curated_case, run_input_case
from ..geometry import HaloLayout3D, LocalBFieldGeometry, LocalCellCenteredGrid3D, LocalCellVolumeGeometry3D, LocalDomain3D, LocalFciDirectionMap, LocalFciGeometry3D, LocalFciLocalDependencyTable, LocalFciMaps3D, LocalFciRemoteDependencyTable, LocalFaceBFieldGeometry, LocalFaceMetricGeometry, LocalMetricGeometry, LocalRegularFaceGeometry3D, LocalSpacing3D, NeighborMap3D, ShardSpec3D
from .fci_halo import (
    GhostFillWeights1D,
    HaloExchange3D,
    LocalPeriodicTopologyRule3D,
    PhysicalGhostCellFiller3D,
    PolarAxisRegularScalarRule3D,
    TopologyHaloFiller3D,
    make_default_topology_halo_filler_3d,
)
from .fci_boundaries import (
    ConservativeStencil3D,
    LocalBoundaryConditionBuilder,
    LocalBoundaryData3D,
    LocalCoordinateNormalDerivativeConstructor3D,
    LocalCoordinateSideValues1D,
    LocalCoordinateSideValues3D,
    LocalBoundaryFaceBC3D,
    LocalCutWallBC3D,
    LocalCutWallGeometry3D,
    LocalCutWallNormalDerivativeConstructor3D,
    LocalCutWallValueReconstructor3D,
    LocalStencil1D,
    LocalStencil3D,
)
from .fci_model import FciModelState
from .fci_time_integrator import Rk4StepResult, rk4_step, sum_stage_outputs
from .fci_operators import (
    PerpLaplacianMgHierarchy,
    PerpLaplacianMgLevel,
    build_perp_laplacian_mg_hierarchy,
    build_conservative_stencil_from_field,
    build_perp_laplacian_stencil,
    build_perp_laplacian_face_projectors,
    divergence_conservative_op,
    curvature_op,
    grad_parallel_op_fci,
    grad_perp_op,
    mg_apply_preconditioner,
    perp_laplacian_local_op,
    perp_laplacian_conservative_op,
    parallel_laplacian_direct_op,
    parallel_laplacian_conservative_op,
    poisson_bracket_op,
)
from .fci_2_field_rhs import Fci2FieldRhsParameters, Fci2FieldRhsResult, Fci2FieldState, compute_2field_rhs
from .fci_drb_EB_rhs import (
    FciDrbEBBoundaryConditions,
    FciDrbEBRhsParameters,
    FciDrbEBRhsResult,
    FciDrbEBState,
    compute_fci_drb_eb_rhs,
)
from .fci_4_field_rhs import (
    Fci4FieldBlobParameters,
    Fci4FieldFreeDecayParameters,
    Fci4FieldRhsParameters,
    Fci4FieldRhsResult,
    Fci4FieldState,
    compute_4field_blob_rhs,
    compute_4field_curvature,
    compute_4field_diffusion,
    compute_4field_free_decay_rhs,
    compute_4field_rhs,
    compute_4field_poisson_diffusion,
)

__all__ = [
    "NativeRunResult",
    "FciModelState",
    "HaloLayout3D",
    "LocalBFieldGeometry",
    "LocalCellCenteredGrid3D",
    "LocalCellVolumeGeometry3D",
    "LocalDomain3D",
    "LocalFciGeometry3D",
    "LocalFciDirectionMap",
    "LocalFciLocalDependencyTable",
    "LocalFciMaps3D",
    "LocalFciRemoteDependencyTable",
    "LocalFaceBFieldGeometry",
    "LocalRegularFaceGeometry3D",
    "LocalFaceMetricGeometry",
    "LocalMetricGeometry",
    "LocalSpacing3D",
    "NeighborMap3D",
    "ShardSpec3D",
    "HaloExchange3D",
    "GhostFillWeights1D",
    "PhysicalGhostCellFiller3D",
    "TopologyHaloFiller3D",
    "LocalPeriodicTopologyRule3D",
    "PolarAxisRegularScalarRule3D",
    "make_default_topology_halo_filler_3d",
    "Rk4StepResult",
    "rk4_step",
    "sum_stage_outputs",
    "Fci2FieldRhsParameters",
    "Fci2FieldRhsResult",
    "Fci2FieldState",
    "compute_2field_rhs",
    "FciDrbEBRhsParameters",
    "FciDrbEBRhsResult",
    "FciDrbEBState",
    "FciDrbEBBoundaryConditions",
    "compute_fci_drb_eb_rhs",
    "Fci4FieldRhsParameters",
    "Fci4FieldRhsResult",
    "Fci4FieldState",
    "Fci4FieldBlobParameters",
    "Fci4FieldFreeDecayParameters",
    "compute_4field_blob_rhs",
    "compute_4field_curvature",
    "compute_4field_diffusion",
    "compute_4field_free_decay_rhs",
    "compute_4field_rhs",
    "compute_4field_poisson_diffusion",
    "LocalStencil1D",
    "LocalStencil3D",
    "ConservativeStencil3D",
    "LocalBoundaryConditionBuilder",
    "LocalBoundaryData3D",
    "LocalCoordinateNormalDerivativeConstructor3D",
    "LocalCoordinateSideValues1D",
    "LocalCoordinateSideValues3D",
    "LocalBoundaryFaceBC3D",
    "LocalCutWallBC3D",
    "LocalCutWallGeometry3D",
    "LocalCutWallNormalDerivativeConstructor3D",
    "LocalCutWallValueReconstructor3D",
    "PerpLaplacianMgHierarchy",
    "PerpLaplacianMgLevel",
    "build_conservative_stencil_from_field",
    "build_perp_laplacian_mg_hierarchy",
    "build_perp_laplacian_face_projectors",
    "build_perp_laplacian_stencil",
    "divergence_conservative_op",
    "grad_parallel_op_fci",
    "grad_perp_op",
    "mg_apply_preconditioner",
    "perp_laplacian_local_op",
    "curvature_op",
    "parallel_laplacian_direct_op",
    "perp_laplacian_conservative_op",
    "parallel_laplacian_conservative_op",
    "poisson_bracket_op",
    "run_config_case",
    "run_curated_case",
    "run_input_case",
]
